apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository-bitnami.yaml
  - helmrepository-tarnished.yaml
  - secret.yaml
  - helmrelease-postgres.yaml
  - storage-app.yaml
  - helmrelease-tarnished.yaml
