apiVersion: v1
kind: Secret
metadata:
    name: tarnished-secrets
    namespace: tarnished
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:dUuuRNYHAJ/8RLEoOMuEj0GgfTzjBKaVmmHgsnpF+cf6Dk9Jl0/onmGU+sg=,iv:0H47GgOJyvJ9LL1eR/Dm9IDDgVT6lByNza/sPD77ebc=,tag:nZOmVt4pH/V7fHH3mV31gg==,type:str]
    secret-key: ENC[AES256_GCM,data:wa/gsvWTI30f7Aqe+rAHL3BVyHzk09LlKDNKqHsEycLQEfniE/r+9y1eFpI=,iv:Ohs40x+RlP95TgoyBoMSnJ3Eqvtgp8lLT2GkYd83+Mo=,tag:T492cZ2GumaYY0IEVR9iDQ==,type:str]
    database-url: ENC[AES256_GCM,data:V03vSIDBwUCth2WEbFQCZYyDIW4slV2+oVun/0Cz6s13XHvvxwVhYem/YWWSDQFVlPlqg8zDqnjhpsx6Ig+jKFoFVuYh65TSwtskfzOHMiLU6CM3hYQADynhBl2tOplA6bBBynRl/RsFKMP37TFVq1M20PPmovDz,iv:hpHV6RmxWaHq3Hj2aMhU28lvJqdBU44wS1yKhb/Jxro=,tag:BbPPh/AP7kgTIsma7wVrSA==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYis5dkIwV295bGw5VEVJ
            cXMzc3NSQXhIdVRkcW01cjB6WnlEUW93SEFJCnUyMkM5UWpSbkpVMitXQ2doT25B
            V0VVaDdHUC9CRDJQK0szbXIzR3BkeGsKLS0tIEVMbUpEWU4zcVFGQ0Z4cXNMSTlH
            RkptU2hCSmVkSkdNVXBrY0VCODE3VW8KdIGGp1vPgcjc9EV6q3eHUFaiHpZkjzPG
            8sT5av8qQgATQ47S85iavPLbfcgTGPICXjNaBQ72uqk1Lbeee9Jf+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T12:23:54Z"
    mac: ENC[AES256_GCM,data:qJ7Zlp7k1qFzOJNTUyCbVS/LKle/19682ADbR8oTbIjOe4ufgphfVnGm2oe1PVL65VxD0IeBSuNk12g2srm40oefGgfnW3SV9tN7wnAtvVzoUWB2WKsSPNerDgsp8Wydg3UvwHLzPvWtoEMP7UTM2t2y+T4xpxxeE7kFSem1+kU=,iv:7N9X/xooAhCGH9yzkeQRUtfVUdGXd365zAG3BSV1aaQ=,tag:5TM9av1zs7z3rJqPXXcpYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
