apiVersion: v1
kind: Secret
metadata:
    name: tarnished-secrets
    namespace: tarnished
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:CT+YHnpJwcJrZgb5wZOLu2Bt8aTHvnynMLKrtYQS4gVvIfFwQUKepsYKi00=,iv:jD6HnWSm5as8Msz/jb3jCmInei7qHFL4mkVmd+FMocg=,tag:StYwlf6ry7gMIWV3ypk8gw==,type:str]
    secret-key: ENC[AES256_GCM,data:hYjY1fgT+R/6Py8RDKW6r70MG2oCcR7uTiibUPwk7hDsv6qAUjGQNjfEgvE=,iv:BI5NfxjKZ5uqmOPIJTP6n0wCz92wYYU9CY+bFLyA8/8=,tag:TsAhQznJToUmL7/PhpUlCA==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZFZzYWZXYWd6L3NMSEg1
            bjUyUldlMHo0bE1NVUkvaFAyUXNIejd2dmw4CkJHeEVmemNqUmtXb1ZIS01IVFMz
            d2xqUU1WbHJJODFSZzNuUG51dE1FM1EKLS0tIHI5Wmd4bVVCQmNWTlBlOGorOUVh
            RDFtaW85Z3k2dFFJdzFPZTRHdWJvQVkKpgSL56+KBI950b5FtBsgPzY3tRUx36xI
            kJwsGTMdB+g5UiyCSq9tgbPn4Ss0BxpGhV01lPjXHF6Toe+RoBRD8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T18:38:20Z"
    mac: ENC[AES256_GCM,data:ibpA6kxpA15/b4a/XhoNj52DH6ZjQjG6v3U0Y4Jc/oGV+mT8tkjfko77QYAwIIXTmxiSBDmFFVMV4ThxCnyYUZ0JMLxs0kh/z9GstFEFtukEDXKssWP+EMYd2EJG9am23ZhMOb0gAr6/tj01eF1/TuTkSgZwNR5/now22KMCMmM=,iv:5GTP5OGBb7wKgBiE9W+cCL7EzVAZyXf00GX+nfki9xY=,tag:pGhFfh8pzF04KHAHiXGZwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
