apiVersion: v1
kind: Secret
metadata:
    name: tarnished-secrets
    namespace: tarnished
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:72FTjJ/ZRSatkrsYt81T34v2IDYGHVIsRZNmvdRC8HvxJMzDwbrjSO/XX9o=,iv:R3T2qnK3d+j+S1GUU0vslPQwJthDhGDBGOI0Z7ZRVpE=,tag:orrBV2iN5CGLr9sf1Rg7dA==,type:str]
    secret-key: ENC[AES256_GCM,data:VMVBfz5/vB5E/llcndvnW0cTwQ1jDiShTH0W+mODgzeL2ixKfHSfqH11sdw=,iv:rtNqSYwngSKJvlDZ/ZdxgzAKmGNpKXTJadnFpp7/Epw=,tag:Iy1mpp5VLNOx8V1w2tX8pg==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc1BWZmhzeHNoZk9oR1oy
            ZExsL3ZaNXUxTHd3dkhCSEQ3enZ2U0I2cm5rCllXUjhicG9vaTFLemc1allVR0ZX
            SnpVS3hGaWt2dmNTNnNOYVJuRmxpYVUKLS0tIFhLblRlTlVMWEZsUG1ISjdnRFJh
            ZkR3RFdXQzhCeEtoVTcyUW80enZ3MzAKPFePBNRHpfYXPSchy2UKF7UPD0Tdoceh
            S8uZw4aSm3TiBv/rEfVpp7M5j78FIGmSXWURITRli77oHJo04VlPmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T11:57:18Z"
    mac: ENC[AES256_GCM,data:NEm7G7V4B5zJoOUf0La2+Smi2cML1fnCMDvEdKvC0LDU2XOksbozj9TNngH6khAboKYlPB18iIwouRb4Z4Hcb7zaYtz4YptEMVH1lymh/sGluUhMqJypInBG8BBrSS50p8uOdkSWoKUS9GUqUmXFT3toF5MCmPzl3g1jC62hfLE=,iv:/i3bzQCX68FQIwTogQgjZa42rmP2EuWTR6k7YghQ818=,tag:xkgY7r+99cDEgngG5w/Ayw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
