apiVersion: v1
kind: Secret
metadata:
    name: tarnished-helm-values
    namespace: tarnished
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:7hjaJnvRJroqDotLTvOnFI4Y1IAZscGXTG3nFmCtC9sk15/LVnnM64zxNPC+eCYumn1GsQunsL0MaqusRuZWcZ7hOT2pzIoNu7s6Ed4Kd3UYiDaqtWaUt0mQ2y6qgkZfnrSuqBR+lt8Lpw9mV+IbrxY5YBgHdWaHqZZF5USEKguIfz/x1lCHWnPIW+HMQf31sTmUVFULIRc4JII=,iv:nWQOe8fzjuZB6ohdyuDWdgiH8K/6fqRknW+XbMN0y+4=,tag:JkA0gjDh8IAUk8DX0ftj/A==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZng0MG1JcDlETnMydFRC
            QmVUYjBJa3RzTHBlbGVZNXBYRkdCUFJmT0VvCmNUTjA5UDFMaTgxZnl5bk5lVlc3
            VXZCZm9abVEzSUIvcm9JL0EyRnp1Uk0KLS0tIDczTnp6cW40UHVneHRxWE1aY0NP
            TXZsbUx0Wi9sclozVzVhc0JiVXlVaTgKhihMw3mKFtTssm76RQRCb3f4AwxJfrpj
            g0fOPXhDyqxVgnd63qQbYsSJGry0hVS5BWq0ca8JezEJ4TuSEKkr9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T18:40:03Z"
    mac: ENC[AES256_GCM,data:1ZkrJCEzA8LLz0XSaB6miZsUXAcLuzslTwssuImZxyRe8V8lP7FbXmxc3bk8fCEtzbc3KfxNE98J4fwmmU2KG8UiA3WoE4UFinQeMM9P25JMFM9zbQWh7SIybXXl/FWQ6LPipXxTNVtPA/5/K9Kfe5kljNUTTb5eDNJy80qm6EQ=,iv:g5CLA2JvqwqNecbpFSkOPPjzpg888T3R8M9POinvLPc=,tag:5KMBbSSwEddUXs9sUHE9ZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
