apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: headscale
  chart:
    spec:
      chart: headscale
      version: "0.1.4"
      sourceRef:
        kind: HelmRepository
        name: headscale-charts
        namespace: flux-system
  install:
    createNamespace: false
  values:
    image:
      tag: "v0.27.0"  # Latest Headscale version
    service:
      type: ClusterIP
      port: 8080
    # Enable Headplane UI
    ui:
      enabled: true
    config:
      server_url: "http://10.104.123.141:8080"
      listen_addr: "0.0.0.0:8080"
      noise:
        private_key_path: "/var/lib/headscale/noise_private.key"
      dns:
        magic_dns: false
        base_domain: "headscale.sarma.xyz"
      prefixes:
        v4: "100.64.0.0/10"
        v6: "fd7a:115c:a1e0::/48"
      database:
        type: sqlite3
        sqlite:
          path: "/var/lib/headscale/db.sqlite"
      derp:
        urls:
          - "https://controlplane.tailscale.com/derpmap/default"
    persistence:
      enabled: true
      size: "1Gi"
