apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: headscale
  chart:
    spec:
      chart: headscale
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: headscale-charts
        namespace: flux-system
  install:
    createNamespace: false
  values:
    replicaCount: 1
    server:
      http:
        port: 8080
        listen_addr: "0.0.0.0:8080"
      metrics_port: 9090
      grpc:
        listen_addr: "0.0.0.0:50443"
    ui:
      enabled: true
      port: 8081
