apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpn
  namespace: headscale
spec:
  interval: 30m
  dependsOn:
    - name: postgresql
      namespace: headscale
  chart:
    spec:
      chart: headscale
      version: "0.1.4-dev"
      sourceRef:
        kind: HelmRepository
        name: sikalabs
        namespace: headscale
  values:
    headscale:
      serverUrl: https://headscale.markonakic.xyz

      image:
        repository: headscale/headscale
        tag: "0.23.0"

      db:
        host: postgresql
        port: 5432
        name: headscale
        user: headscale
        existingSecret: postgresql-credentials
        existingSecretPasswordKey: password

      derp:
        enabled: true
        stunListenAddr: "0.0.0.0:3478"

      policy:
        hujson: |
          {
            "groups": {
              "group:admin": ["admin"]
            },
            "tagOwners": {
              "tag:homelab": ["group:admin"]
            },
            "acls": [
              {
                "action": "accept",
                "src": ["*"],
                "dst": ["*:*"]
              }
            ],
            "ssh": [
              {
                "action": "accept",
                "src": ["group:admin"],
                "dst": ["*"],
                "users": ["root", "autogroup:nonroot"]
              }
            ],
            "autoApprovers": {
              "routes": {
                "192.168.0.0/24": ["tag:homelab"]
              }
            }
          }

      ingress:
        enabled: true
        className: traefik
        host: headscale.markonakic.xyz
        tls:
          enabled: true
          secretName: headscale-tls
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.tls: "true"

    headplane:
      enabled: true

      image:
        repository: ghcr.io/tale/headplane
        tag: "0.3.1"

      config:
        server:
          cookieSecret: "jeWnqQMQ22x3/LTP196Wd2WH2wz2twQPTzBPnn4tNhM="
        headscale:
          internalUrl: http://vpn-headscale:8080

      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
