apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: headscale
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "15.5.20"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: headscale
  values:
    image:
      tag: "16.4.0-debian-12-r13"

    auth:
      username: headscale
      database: headscale
      existingSecret: postgresql-credentials
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password

    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
