apiVersion: v1
kind: Secret
metadata:
    name: headscale-domain
    namespace: headscale
stringData:
    domain: ENC[AES256_GCM,data:5YgQaDL3ysgFlVZzeACFrVzdI5k=,iv:ADN+sq0tiTCmuZtUaiXYeRqiyTGjMHYhCIc6ad6Q0g4=,tag:8WLMtSe3ccMtiq1/gI5iIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UzlNZURTbTR3a0tMZDQw
            UlpGMmRVQnczdHdNUXYzNUhsVHFicGZjOEVNCnhrYWJtRDJuRGJySlUyKzJjVUhl
            UFpWM3NxYXc0eFF3SGgvTUlTaFBOVkkKLS0tIGJCckVFdmZsUm5rL3Y5UDl0bWVa
            NEJuR1NEY0hYanRDblBKSlFvRmZJd0EKHP/sTVBcyZ+aoKPO7BNOraOoQYLHXfKp
            hnkydjf5nMj26khBdbC+WrAH7kZCqftLmq8FQPbk0dq5RI0k5AlFSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcGU2eFpKRDNZNnVnaHVz
            YnhqeCtXN2pIUmZkSU9uRGVJSHdnM0MyUEJRCnY0OEpEdEx2K0dQMmpVS0JaN1Ji
            dmJ1ZS9zNGhBbHB1Qm5TRkRSamVRYkkKLS0tIHU4ZjFMMmhtMTQydTlsbHR6TFpK
            SlFvTnZ5YnJ0cVRGNVF0MWZ3ZWpKUW8KG3sut+1xpA9cZwK4X8aOFn+pawM/AfYb
            f+VhaIdiU5zfl3uNkhYaA/hLuCIriqORdN0kPzx6u80MSdA4shhZuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-01-28T10:21:41Z"
    mac: ENC[AES256_GCM,data:53kCXO0wu69lpfw48kmbzcT+hxwRd6rBq4Sz6CNA0x9SNa7Byt8IWIPrLgT9lTvvqtUKNvWI373Y/E1RCvgsebbdiTNf+REqfNefGETPku/H/rNCyvoriIGV9v5j/k969iXO6MkBlFyiv1NcGqQ5VllbmPqaKK8KlKMl/cNcO0w=,iv:ZHAa+S9nuO6EeJ/N/kxFnjgtweMj4W3Jpk3soEXgIB8=,tag:+lLRwCWAo3oAZLEVl/Z1AA==,type:str]
    version: 3.11.0
