apiVersion: v1
kind: Secret
metadata:
    name: headscale-domain
    namespace: headscale
stringData:
    domain: ENC[AES256_GCM,data:5YgQaDL3ysgFlVZzeACFrVzdI5k=,iv:ADN+sq0tiTCmuZtUaiXYeRqiyTGjMHYhCIc6ad6Q0g4=,tag:8WLMtSe3ccMtiq1/gI5iIQ==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVXNXeFBPckdTVytuaFl3
            TnIvTDdZMllDMkd5SGIzUDVOYVFXVWEvU3pRCldlL21MTXR0eklyejRoOGpOSE1w
            clgyL2w3LzFVNGN1S2VpejJ3dHFHa1UKLS0tIE1OUUN0ZWMzTWh4NlpZRHdDTGxt
            UmN3VGg1N0Rvc0VMOCt2NnJZak5GZ3MKaLO6a+By29xLsp4W3GR6ROqd8Sdcp+X2
            LtfH4S1fuNCJi2+Je+bvER6tN5FI4c8+g1U/8BTWbTDdXDX0iD6MQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T10:21:41Z"
    mac: ENC[AES256_GCM,data:53kCXO0wu69lpfw48kmbzcT+hxwRd6rBq4Sz6CNA0x9SNa7Byt8IWIPrLgT9lTvvqtUKNvWI373Y/E1RCvgsebbdiTNf+REqfNefGETPku/H/rNCyvoriIGV9v5j/k969iXO6MkBlFyiv1NcGqQ5VllbmPqaKK8KlKMl/cNcO0w=,iv:ZHAa+S9nuO6EeJ/N/kxFnjgtweMj4W3Jpk3soEXgIB8=,tag:+lLRwCWAo3oAZLEVl/Z1AA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
