apiVersion: v1
kind: Secret
metadata:
    name: headplane-cookie-secret
    namespace: headscale
type: Opaque
stringData:
    cookie-secret: ENC[AES256_GCM,data:idG4ZeqTRAD/sSkNwSICLF7IUlZiOGujImW71IGkFcT7/T22QKTFAS7Dpis=,iv:pwBi5VaToM9RUDON0J1Pq/3luQfWq/vMRDizGZ4mK/o=,tag:uBULcyUZ0A2mNnlVG8LWgw==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByekRKTExyNUtBZWs5WUVj
            M2FrdlBHM0pNOVNFVHdGZVNOVnl3NlYwRlhJCmdJNkNxWXN5OGJzazg2QWR5cTZu
            SFMwSStUNUl6d0xtbmpQOUd6Z1ZoWDQKLS0tIFgzZVpVTzE1aTZoTVlqc1lDVkVX
            czFDbGpyVVp1c2NWbkhHK3RXYnVaVnMK+SyO8aZ5mJuf2KMjM4n2kAIECHl2nNWV
            DKdSRTUj+NjRzcRUTTGu38RX4S0HXfUly5hfUVOGrsm/sgoZ6Ppmhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T13:40:49Z"
    mac: ENC[AES256_GCM,data:+yKuCh2krXEwa355y7Z1bzRaf46+RBa6Cq5UCUVB3TzUYZXZSDDArZnlRuLp8m6hee/a3lScqgRL+sTf+8jOhV2D/TTKszNHL7+zYqzzGAx+iOOWkT9XqECHpTcguwi0m4cjrp+tlyVoZOseCcNod4bf+BKOn+3qPKkMUNDmOFc=,iv:WtN0XnszjXEvsBfLTuHWix2Og2wFcFoWNltwmPwj4vs=,tag:qgx4xn/x3M5Yv2rNMHNHHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
