apiVersion: v1
kind: Service
metadata:
  name: headplane
  namespace: headscale
  labels:
    app: headplane
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: headplane
