apiVersion: v1
kind: Service
metadata:
  name: derp-udp
  namespace: headscale
  labels:
    app: headscale
  annotations:
    metallb.universe.tf/allow-shared-ip: "traefik-shared"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.220
  ports:
  - name: stun
    port: 3478
    targetPort: 3478
    protocol: UDP
  selector:
    app: headscale
