apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glance-k8s
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: glance-k8s
      version: "v0.1.3"
      sourceRef:
        kind: HelmRepository
        name: glance-k8s
        namespace: flux-system
  targetNamespace: glance-k8s
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Resource limits
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Security context (non-root, read-only filesystem)
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
