apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynacat-k8s
  namespace: dynacat-k8s
  labels:
    app.kubernetes.io/name: dynacat-k8s
    app.kubernetes.io/component: dashboard-extension
automountServiceAccountToken: true
