apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  # Request database and configuration (~1Gi). Alt: 5Gi (many requests/history)
  storageClassName: longhorn
