apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-auth
    namespace: media
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:c2fTf0Unl5K0ZmjYkhHLPOfNZNopJkTPdEHpZENYjMm2V24Bkqq/q3eVHe0=,iv:e8Ro5IhZyn3BoDLO7ulnTkYOtOiDwHOK9DR8mAMUQjM=,tag:JxXRJO2JZajnjxbdjlXIOA==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZnp6MVdqcDhWOG9nNkNM
            ajJoWDZVNnZwZnVkQ2MwdEsxTjBabzhNcmw0ClJ5OFJpdUc0VzlVNW9nZjBNMGtp
            WXprNEcvS0FPSk1sMjBaYWovQ1hGUmcKLS0tIGtFbVlEMStPNTNmS2RPQU9ZbVVk
            cGdZYWZZenovSkRoL20rc0ZHZnM2T2sKmNbSKtlyQYdwpOt2XUtqx79u4PUjz39h
            0BJtwll0aRn0W/gbolhdo6ZhGdSZ7WJzW6za9pCpkkRRJElGSPTj4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T08:24:43Z"
    mac: ENC[AES256_GCM,data:sThUcwH73jETuXqWxhbMfY6eRUab6kIEtVJn6zY6aURRIk4iN8lDCyKis+YPVQ9620Uo6k/a0B+xua37fZCM3xOujX98RdBCpAOe4ZtDWuyhp1/2062yR6A2KjF2ZN0ji6LjUXaIbqbiqjPPci0Z7H11BoGnVOb64P0UgrRTohg=,iv:o1svXFh1FakxXxocxwj/zoC6ERNmpphKLoTMZqH9Em0=,tag:OJ7Y2ohKvYudQnCiuNufcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
