apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyseerr
  namespace: media
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyseerr
  endpoints:
    - port: http
      path: /metrics
