apiVersion: v1
kind: Secret
metadata:
  name: wireguard-secret
  namespace: wireguard
type: Opaque
stringData:
  WG_PRIVATE_KEY: cCagxPNKpbnJMAnhyFHkwGKk/Gh47hLuwgNz/VEMlWU=
  WG_PUBLIC_KEY: /hQBFCFfotaAxQywhz7lFzS+2QakVrZtonRnj4qFtkk=
  WG_ADDRESS: 10.0.0.1/24
  WG_ALLOWED_IPS: 0.0.0.0/0
  WG_POST_UP: iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT
  WG_POST_DOWN: iptables -t nat -D POSTROUTING -s 10.0.0.0/24 -o eth0 -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT
EOF && sops -e temp_secret.yaml > infrastructure/base/networking/wireguard/secret.yaml && rm temp_secret.yaml