apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: media-stack
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/markoonakic/homelab-media-private.git
  ref:
    branch: main
  secretRef:
    name: media-stack-auth
