apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
    release: monitoring-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
