apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage-app.yaml
  - storage-db.yaml
  - secret.yaml
  - deployment-postgres.yaml
  - service-postgres.yaml
  - deployment-mealie.yaml
  - service-mealie.yaml
  - ingress.yaml
