apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: mealie
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:34oayQFHb1wzYiPxyv3hWUFS+rshZ+aOaNV0ENtS4jI=,iv:gSQvA8Gmx2hbjBP2VbzPnuEnF9eAHKQN9m3WuaDW3aI=,tag:RQF5B+JLrascbhqrC4E+cQ==,type:str]
    openai-api-key: ENC[AES256_GCM,data:LIZv3uTPxNY2rczMi6R1rOPB5B/py0ktZXxurftoEbPTUyM6wf0AO1d0VJWQy4dRfOa2Cb5EjPOEZJ7zGJ13JEAAEtjgKcr9BAlGzvNduFSlbJ4TYHnu1zHel5L+Zp+zTUkhTsz5VRdqiwdWwAd+xlPjVMx3/J4lsj0L8xdwrQN7z6vp7ym1qo32fg+2ZeCTQCS7bKELhXMe8/k7Lh7/31h4wBY=,iv:cPkLIm/rspeqSV+EMyCYyZpQVAkjKQ+iy/YgvcjoItU=,tag:C66TeC46a5wODK2v+fajVg==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza3RSRlowQ3NPRVdhVlBB
            QnBTc2VldHF1a3hmbG4ycFBqaW5FaGhxYVZjCjdPeGxTM1NXbG9QYVRmb0Q2YjBM
            N0hNNUlmTkdYWVQ3LzBKeE5Wd0s1Z0UKLS0tIE9Uc1FPQk0rcjdzVzdEWkVSbjFu
            QWtBdFNaZ0dYZVJYY0pjdWFheFB2QXcKMqeED2QJpS8rNqiKWBkl6XGwGhhSfFoq
            +bwGhNGCUrWJ4d9gUOuh2tImO3KFghM+wtJ/h4t8uFe0FfZom9CZYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T08:02:06Z"
    mac: ENC[AES256_GCM,data:ngfwfsY8NbXBYpp9+Jv10+akrs4eHr0TXL8/BXwNNGwO2ctM0Cy+SFrrXD0baPifDtbAMJKR0bOcFapE+8bZte+Lm1VsnEWTiVG1eGnKrsrDUrbKjy4G5VwTCFt8rPGUzwgvtrzyfMZsPcgXhKOb37UrYDOp4JuGZPngLASOwcw=,iv:kJhokNrGCAC+P3yOI0m8jtnevrrTWhn1//Jrnxr72oA=,tag:9VSXOg6EtqtFD4b2Qb9R1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
