apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: mealie
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:34oayQFHb1wzYiPxyv3hWUFS+rshZ+aOaNV0ENtS4jI=,iv:gSQvA8Gmx2hbjBP2VbzPnuEnF9eAHKQN9m3WuaDW3aI=,tag:RQF5B+JLrascbhqrC4E+cQ==,type:str]
    openai-api-key: ENC[AES256_GCM,data:LIZv3uTPxNY2rczMi6R1rOPB5B/py0ktZXxurftoEbPTUyM6wf0AO1d0VJWQy4dRfOa2Cb5EjPOEZJ7zGJ13JEAAEtjgKcr9BAlGzvNduFSlbJ4TYHnu1zHel5L+Zp+zTUkhTsz5VRdqiwdWwAd+xlPjVMx3/J4lsj0L8xdwrQN7z6vp7ym1qo32fg+2ZeCTQCS7bKELhXMe8/k7Lh7/31h4wBY=,iv:cPkLIm/rspeqSV+EMyCYyZpQVAkjKQ+iy/YgvcjoItU=,tag:C66TeC46a5wODK2v+fajVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOclBLR3FmQkJKdnBqb0p0
            UWlFVWNhbXkxaTBham52QndjTkFQSTEzNXhRCi9pckhyZXA1YlFOOGRrWWhpblQ4
            ZTA0SG9wcHg3LzdJTVc2Q3ZqdS9JTk0KLS0tIFNpckd1dFdMc1drOTFvb3ZFd1hP
            R0hCYW5GdkdoejJZcURvejR0bUZKRWsKl6vYCel++ioaYC5vio4XYvr5Si2wE+Pi
            NaPbjzcNPb+T/rYAdI2I/Gp6X6glB7Nla955i/gWlzUboQbNdA/PvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZEk2OXdic0NxTndqZnhX
            K25iRVlMVWFnWlJXQlNnbGhwMkkyUUpmL0ZBCnBFTW1zenlkZTZTckVVZ1RqZDNv
            eHJqZXo0MlRHTlZzQnRxWjEremNEUlkKLS0tIGJYWmVGRzZEYzVLL2ZWNlBRaFlZ
            OGZmQjJkajFjbEg1U3NseFpGYUFyVmsKHRgv0EVCKoZlcJss5Ta9zl1L5SCiuj6/
            FBWIBVv1YBSj2kB4hJJUvs0KS1NChaubhOEXx00zj0h+uU305a4Rqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-04T08:02:06Z"
    mac: ENC[AES256_GCM,data:ngfwfsY8NbXBYpp9+Jv10+akrs4eHr0TXL8/BXwNNGwO2ctM0Cy+SFrrXD0baPifDtbAMJKR0bOcFapE+8bZte+Lm1VsnEWTiVG1eGnKrsrDUrbKjy4G5VwTCFt8rPGUzwgvtrzyfMZsPcgXhKOb37UrYDOp4JuGZPngLASOwcw=,iv:kJhokNrGCAC+P3yOI0m8jtnevrrTWhn1//Jrnxr72oA=,tag:9VSXOg6EtqtFD4b2Qb9R1A==,type:str]
    version: 3.11.0
