apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: mealie
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:1Ci4EBQGIr0x5dIYNDE4YPhCqO8MEhKc3WiHqCBR5ToQXvllmnCNXpB9rrruiUU8,iv:Ukp/8adZKYGHGxN9bb2z8Drakak/u7lfocBO4IpTOys=,tag:VnxqD48YG8i6EFw/U6RKTg==,type:str]
    openai-api-key: ENC[AES256_GCM,data:aaAGuuKK5roQz2ixpRzgeEq6riZrHxrquLbjnsJTWoJhK9sCtpc4ueTaSPS/yWbhnR7OpWneK7f69MI/h6UZsrKb+ysDa0iWTgVjFf8flfC0ZRR/LqTKpD2krcBHTIcxWDZkBZugmZydo2MSZLp47NGAY95scgOGCW8xQC+6kBLrfpThdejqo+RwDE9IPzWjHhiAGPb7psg9fP4lkRz+nTHB6oA=,iv:64mNAITMrRTHP2I5GW37TRt8j5ZYKBjEdvSeX+QLu2w=,tag:O+QtbRo9DAEw+0q6uVPN2Q==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUWVjK2tPV2xlaHplbDhR
            QjJHd2UyT05XTlR4QlpmbisyaFdBYjhQNFVFCk5SQ29JQWFlOWJNMzR2NjJJYlJj
            U0wvN2lEcUZNOVlHSTNCdTdMWjRjNTAKLS0tIDBTcW1XYjBmNFl5UEJLMXBld3FO
            Q1VEVjltc0pPeDdDZ3RsUHl1WFN3TDAKkrQDJ2h5Z45i4dPG/NAG631We1h7vUz1
            q505HUNbkm+Vh8mpJIJjTDfpgnhtiN+Eg0QiK+MmZuEmO2vvSFHycQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T07:37:38Z"
    mac: ENC[AES256_GCM,data:o7BJHfHZfDUEEm3Vt3Sg0ElVSiRDHAe2nDP+0uHauChBeuUMSNAqdM/k8PhTW1PXQ6YE3j10x3h9lKO9aQPVqvseKAG7WSgUmWcJ1VyegN1nC/wzJQl3sTI2udC9Jyc8EUXdVzw6zJktzY55Neuakqa/IeTuggvy/t+0neR/bg0=,iv:VaAiCuxL01SwBmPPvoYPIko+Iv6n+wEAN2xL3HiMt3o=,tag:L9hYB5/hnq5/YchR9sYxLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
