apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: "2.6.0"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: media
  values:
    image:
      repository: jellyfin/jellyfin
      tag: "10.11.4"
    nodeSelector:
      kubernetes.io/hostname: talos-cz9-9tb
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      media:
        enabled: true
        mountPath: /media
        existingClaim: media-data
        subPath: media
    ingress:
      main:
        enabled: false
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
