apiVersion: v1
kind: Secret
metadata:
    name: headplane-api-key
    namespace: headscale
type: Opaque
data:
    api_key: ENC[AES256_GCM,data:vaGy5K+I3Yzfs2OclSWNHfGFvjKw14f8um/Svqq/xKEJ+utMWWKmGkxhXErkXk685mWbpRrsK6Y=,iv:WOTl5bO/yDEx5nhX29sBRMx6b3WzULSvMKv9gc4bySs=,tag:tUdHopxHQ/g3v5gcKnDaeg==,type:str]
sops:
    age:
        - recipient: age18tm3eq9js8cx3mhn6qersalyezzh3302vuewlvkmycs72qpw43jqmjptxt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZGwzRm90bzFKWDBNdmRm
            WFlWRzdpM3ZHcnNKS2FqNnpaR1pWYkkzckNNCjBIc3czTlNmUVd5VHRaejA1NDJ1
            cXRIOXU3SktyOU9hZmFqaW1vTWhrSWsKLS0tIDBwOG1lZ1gwdUVoRmxkNGd5WHpz
            bCtBRnliUXpPZnhBd3FqenpPTVl0WmcKsqjGH2tKpo02ak9Ztt1tbfpEk7GMoQhm
            2cCHE2pSUEEVb/fB18e5TuEwdyOgilxSynkymtFXBSQu2ZflrdQtiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T14:31:46Z"
    mac: ENC[AES256_GCM,data:rgZcmedTw9eL0aukpiUQwiGshRERbhJSMJd5nIroL+xfeuuTv6iuMGpXMmoznzrvtQM/+spPXVvI7kMaKaO20LQ/2Nj6alY/P9GgKklzuM+oGmZeUcs3qzYDsMZPQooMN/aEz7/EmFYQQHJXEQe5j4KNbLn1HTf169GW3RGRaK4=,iv:VjmLMvGyQVgKcL7A8bXFm3/iN6W3WeiJRDd2xRHec7I=,tag:iLLPoQ0FNDOsqtJjvrFLaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
