apiVersion: v1
kind: Secret
metadata:
    name: headplane-secret
    namespace: headscale
type: Opaque
stringData:
    cookie-secret: ENC[AES256_GCM,data:BpCHgpw3wlDSUDYIXlV8SfNWEdxeZNP56G3dZKHaM3g=,iv:B/GhVCk0NS2c69nCoKcrCfQxIBBNY78gijot8sgFAgU=,tag:IApVHlppcFrsfAcYR5xPtw==,type:str]
    api-key: ENC[AES256_GCM,data:A7hWsgtv2SSK1DQjG7I3Jk4x3ceyD5mFOyHxm3Ky128D85ihTLWkBQ==,iv:mTaKS1OHOh9q3n0aLQJ9AB7p05DQmn3faPXBsGr3wb0=,tag:/fDWDTZRHjfnM2VX1RAurQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc25ncW5nSHFsaWd4c253
            UUhNOHlrZUowRVFzSytYeUdtU3F2WjI2MnljClozYjBrcjlWeXJ1aXA4NUdBVldv
            ZnkrWFJwbHAxVXFHOHpUUldUNG51MzAKLS0tIDFpVDVsVE1pd3BLYm5FeVlsdWMy
            Tnhqbm45Vlg1bnJmNCtqZXMrN3JSZHcKf8n/KUY1JtPjE7dM1Jb9H2vePYUSIGe2
            PUdUoo/zCHe5ACpNoQ+uJL+JYFKreu7+u/AMj0RCVAPECBf48IIMgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M2lhS2ppaG83MWliRG0y
            a1g1YktvbVVPVXNSRG9obldMdnZZUk5sL1ZJCnpVQ0t6OVpES1ZwVDNWaWt6OEx0
            SUpHcjBldlpnNU9iekJNdlVzRS9FRDgKLS0tIEg2cVdmOGNQK2lmUzdTdGxUMzhZ
            bmVUZVdrMnAwZzF2a2cwRjhlTFRCSTQKvrTIxSoclCRrvJhFDz/r5yiIKFqXvmMu
            v3rQLPhdduT654sIEtpV42c5TOPNSPFbCjfWqWFKBBM08o3zmkF0Mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-03-26T15:39:34Z"
    mac: ENC[AES256_GCM,data:itXX9sziUYiKk4GRe5qoacJMP6fqadTLfEUQxVNdUCEvjPt/N2+yga58rqv08Wf+2hYPWXjmnGMYuq+msKskxNpn7iyPRZM8R8Ippp4XygSHxI/wR26/7a/ktRs3H8JIaT20FeV8D7MikAAMg3mcozfRIVGNh20IIeXHUoXaKv4=,iv:epcqyyCydhAyWVHH0dAeAeIHY4Uyt2F8xvsWykNZaBM=,tag:OHP8fz+eSKyKUQnC4B6eQQ==,type:str]
    version: 3.12.2
