apiVersion: v1
kind: Secret
metadata:
    name: headplane-secret
    namespace: headscale
type: Opaque
stringData:
    cookie-secret: ENC[AES256_GCM,data:BpCHgpw3wlDSUDYIXlV8SfNWEdxeZNP56G3dZKHaM3g=,iv:B/GhVCk0NS2c69nCoKcrCfQxIBBNY78gijot8sgFAgU=,tag:IApVHlppcFrsfAcYR5xPtw==,type:str]
    api-key: ENC[AES256_GCM,data:A7hWsgtv2SSK1DQjG7I3Jk4x3ceyD5mFOyHxm3Ky128D85ihTLWkBQ==,iv:mTaKS1OHOh9q3n0aLQJ9AB7p05DQmn3faPXBsGr3wb0=,tag:/fDWDTZRHjfnM2VX1RAurQ==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid1VoYTR6ODRna05UckQz
            MFcweGw0a3V3cHlCaU9vOGdFRWt5dVVKVjJrCnNVcFFSZXROTXF0RktIUmh2M3Fa
            V281OVB5dWxZR3NPMm9JT1c2dDFiRWMKLS0tIE5uRThjREE3c0c0QWJQc2VCSjcr
            RnBTc1Y5Tkc3bEJvdlUzRVZQa21KRUUKhndKeGZxy8i7Y81scDrs1AS+v78G9m2/
            AD1t6fIcv32k8yqzWpF1x7oHLqLXXzLBoa6raYnbLJSORqMEZp8bhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T15:39:34Z"
    mac: ENC[AES256_GCM,data:itXX9sziUYiKk4GRe5qoacJMP6fqadTLfEUQxVNdUCEvjPt/N2+yga58rqv08Wf+2hYPWXjmnGMYuq+msKskxNpn7iyPRZM8R8Ippp4XygSHxI/wR26/7a/ktRs3H8JIaT20FeV8D7MikAAMg3mcozfRIVGNh20IIeXHUoXaKv4=,iv:epcqyyCydhAyWVHH0dAeAeIHY4Uyt2F8xvsWykNZaBM=,tag:OHP8fz+eSKyKUQnC4B6eQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
