apiVersion: v1
kind: Secret
metadata:
    name: radarr-auth
    namespace: media
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:HzWPV6ehiAMFVeumksXXRsGQR3K/DwP6xqYxFwaByzq+TlXOQfpCb3mw/ZQ=,iv:2liK29viihVxtu4Y9uMXrW4AilDWIm7GMzJSegnn3F4=,tag:aK0mpLJCF2GttTbsrm8a9g==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbzVDV2dLemQ2bFJqUnB3
            aXpRM1VKMFpienFoMzlzMmM4aWxaZDkyaUVnCk01bjZVVlpsUE1jYXRrMEY0V0NI
            c1JlTk10Wk9aRDgrdE84STFNa2JCblUKLS0tIGs2dkVLKzZ1NE45MUZ5MzJIUFcy
            MHNPU1FSbnBOd2k5MkZBa0krbWNmRncK8J68yH8XGBT1Z3MsTOK8gwBOT9XAREtW
            on3Iy9UbyQp6KW/+kv7H8HwN2H/rb8+FEkSSDsqUBMRz+QMaUpcHvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T07:48:54Z"
    mac: ENC[AES256_GCM,data:XPtDUjNMaWzLylq6t9e06N4owi8Xa+x3oc9oRgJ1/Mk5lOevmvaavmeRF9mYfOObIQqqXzYJbhLjnf4Mp+FPLWOSIzjJq8wPU4Lp2Pse0JtyQW+P+PJCh5V1Mu0yb4PWdiQWNIoJl60zwuJl2z67fEHipvMEoImT0ZPpoPODPEw=,iv:NbzDn7iS+VaBC8H9lQfAuBwjDJqJL5k3zDAloceKjUw=,tag:opwB6mWKXg1FnbMnXmRMMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
