apiVersion: v1
kind: Secret
metadata:
    name: glance-api-keys
    namespace: glance
type: Opaque
stringData:
    HEADSCALE_API_KEY: ENC[AES256_GCM,data:4vQRtZq7uHD2BZBxktqbNVFMXqgskL+N2A2Et/aI/+8YaX2k9uHetw==,iv:fzv2D8gTxjhpw8Pm+4XpSG4MpFvhiEFKIhFR3NuLfT4=,tag:ui4acENKoUaZP3FgSFfrVA==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVVloVkxzYS9tTTBVYVlq
            TkxZRjRzZHpvcFh6d3U4bTcvM1A2MnRnMzBRCjM1b0wvMWdwSzRTcmh1VENUUkY1
            N0x2RWIxV0xwQUxRR1dwNEZjWXhHTVUKLS0tIEgrUDVmV0dzcXptN0JNU0kwK0FG
            K1V3T3oyNDI5b0R5czhkU3pmU1lJL00Kjnt8bV7pytrAv/C+2pTqUAM6g6MuNV2u
            feC/1Cs6EspnUQxwKq+IB3ftazbT87oIv18EaqLHXn554aclc27kxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T14:49:00Z"
    mac: ENC[AES256_GCM,data:awBIpmSkz9RaJQRr6L5QNFjFmTgBMgLqSIJhcWL2iHmzkqlxD0PyJo2s0J0mmUuZmg5nrVdXELw8TRXa06YOjTfCX3iFqQpXVkqu8kHfu149Xp64oSV1zIK7SVQJcA408SAvg9WcF2aFIRsdQRnJ8BQ9jLczFOIPG9UWq0JyPY0=,iv:LIV1jZUDj0r9m10LVLZyUd9fq53dPqgCzGAtbbJdRRY=,tag:V0aYw4MSN6vhKvcyIhGAZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
