apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secrets
    namespace: vikunja
type: Opaque
stringData:
    postgresql-password: ENC[AES256_GCM,data:LKHRyhxlrp1XWZ9fiLB4Giy9vCWygXUtOaYaxjmqVGU=,iv:JyrownYf/QO66uLWZhuqaNUbEp4YFIBLAb/rMc4iZts=,tag:TyVccBw+VABx1LNdftfMsg==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V291c1pJazdTK29VTDdI
            VUdDRjI3TkJNUHpKaWJSNUswMk4xMUx6blE0CkJab0p1UmFad1RLTjRFamljMjZG
            dmIrY3lhSENReTVWOEY4cWJ6WnZmczgKLS0tIE90SWFOV0RVZzhKaUszNnEwSW9p
            NktZTk5pcjlSV0FzK1p1RVVKN0NrSDAKWeKrX32O/QE6L4RREQqCfVKn8FFmYsvs
            Aqo4ErSdeuNrgjNg4oeHqkt9gOGoIVVzo8x2aEKS/hDR/wc7LyaiVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T17:09:04Z"
    mac: ENC[AES256_GCM,data:Q3coZBo7ne7HAfKe53fs3U70jrafsZT609itMOMhkip74H7fAB3jqpJADo/r8g2jW8qZMNW/kdvaHnRgZKLAUQplJ0qztprFmE28TSyKDHYRTxrrXVjV6co+x79dPhmVI4k8PMMiYRbdngRmApJIrIEofLjITu0LzZQmxsDlKNU=,iv:xfFaapgjlseK9uDl6D48H42264/5mx6hKeHWeb2ZGdE=,tag:OiBvY8ebms6ZN86X++V1pA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
