apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secrets
    namespace: vikunja
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:61QAhmfUsgwu5QKr1kheAs3KwxwfwaKK/l+duVuabto=,iv:yYHMV+dKgwxdvcJu3o1IfpJmS7Op/3ONKiZTakAbrII=,tag:HPBmb/GhEkN/H1Zr9eNqvQ==,type:str]
    password: ENC[AES256_GCM,data:w8Q8nLKqX514XeKKWjj09MkwwUQBreCDP8/zzCVChT0=,iv:PSX1PUR4wGXqYmbDFLnwScA1xHrdSQmA7G2m9jTfOVE=,tag:wnd0Ue7CPHszRd+eJ/HX8w==,type:str]
    jwt-secret: ENC[AES256_GCM,data:bPj4hALzVVAfifOJ6JVHBDUUhI7M4Fy8kMaUxG2SDRgjHGF8HmxIWZhbRSY=,iv:O+chnCTkXigXzMLS7jZ87FYEkKxAGUYVIRN7EY4pNOo=,tag:ltgrkNTXwv2jP/A4sfhJ8A==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWjg5K3NlMjJFTlpsS0VJ
            czErNmlYcmc0SXpvOEFpWExXY05sOEx5WTIwCmlNUnZ6TW94aS9tdVY2SHUzUVlP
            SVpCWkdVNWJoN1RnRzhTWEFCVWZNa0UKLS0tIFBQUkhFbmlpQWQvY2lxQ1VmY283
            ajFpeCtUWXlSb05kcXVnQm5kSmNVZFEKDid0VESIS29cHS4LtjEw0V71jfCoyW6X
            g+PdOVjZdBsBBsFF0198eulv2tEOmbwAWyjTY0XWY6l5dvgueHxDfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T17:42:50Z"
    mac: ENC[AES256_GCM,data:9IRmtWoDqW2AMWoZDKuTnJSAtZSZR19z8TS3gV3NcbMr6GGG0/8rdHTeSG1v8S5rdOKkXYiNRaSgQvIrOLufsG1JQny8ouOg6NVPujhM5MuNtkOm172BAmFfkdAX7NIqnEV6veHUDJKXgZPq3nZ7n8ntLjB90B4J37GylvFyVQY=,iv:5vUe8GfKE3E9+gmMsWFp58CDR7QWoc765I/spwxHbt0=,tag:gRojIKjafe5E0bcWNbadCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
