apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secrets
    namespace: vikunja
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:pGcqN9cwo8hWuhv8SGjzmZqxWf5ZJvvzKYEphMUd+l8=,iv:v8NjvuuPkxoY0e1IysW3VHA5HCn8R99u5wtwBHEY7bY=,tag:BoVJjG5l1I4VBADLoutWCw==,type:str]
    jwt-secret: ENC[AES256_GCM,data:xNo6IaoONPHtdUD8qjvKu8bpMnlb2jajyYYXaz3Zev5dKwn2WMZ+fiSxvlY=,iv:paBkPqBWUrlAai7Kos/dcBzdPpllKqBjLagjutj1I7Q=,tag:R7Skx+lDXvuFbh8oIcNpLA==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb3BrUGF6UWdFcFpIY3oy
            dzduY2phdEUwd2lDSW92KzRNN3V1RHhIUVJZClNncSttRmVrRkVMTEVlV0V1V1ln
            MFRJRFQ4K3k2MnhvOXlNL2Z0cExSeTAKLS0tIG5kdmZlMHkwclRWSkVMWVVOMjVv
            aUxJSVN3c0NBL284Um9kQTJFaUFKYUkKYGHm1tD8vHDWIBMWfjUcXOWDDHoJniOc
            8mO9PybqWNwCLf9UhVWpg3GcscdwkJ26LaxZqYKivcSNo5WclBYVVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T17:50:10Z"
    mac: ENC[AES256_GCM,data:NrPrjlGyiBI9XbFgGKLgEOhcDBbtGUqaf4+tnWXLAkdzmO/SSTQTNN+jGV1l/kM5fsFwO7KhELKJQl7SpMp695PdK1HNs49masarpworBVDg88kgrFHcGzBF4NMINTUvvVKYfoczTyQvAKo1AaYcC4wePvgyUGoXg7gjgCpQZW4=,iv:WbJKo32IVQtuon32j7b73B64WxYX4g1INn5PzGYQwu0=,tag:ooDi0bcSPEv9sbZiGxXdtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
