apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:kGSxQzo=,iv:c4Mhv5SrN0dVpV2JyjogY0a8NeHXI3Kg+gabGuSU/e8=,tag:WbAZlF9e67bjOqvmhRHJjg==,type:str]
    admin-password: ENC[AES256_GCM,data:hZsc5kAXU6O3A9nc7+7lFDIioHFP9bSR6n/IAwUblZRdfVgjVqDdCoSsPmk=,iv:xBXTW2qezqSOXFNjmTtqjsla+eqdK5qosKO94QyyiCM=,tag:5ukshkwXvzscdSbQUaaujQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbUdKdm9LYmsyWHFFMmlZ
            N000Zngxc1dPUFBodXRwNnFWNGRxcS8zWnlRCjF5OFc0Y3pWVEhwRzkxbElwc3da
            S1Exd2ZaUVRMQ2RXTnJCdWZINlFSUmMKLS0tIE5MMTJ5WUtvbnVtSDM2VFJZN2cy
            Ui9UeHMxUXEzd0NFU1Zwc24zczF5S0kK9OKNREqAl9gqKIhyEGAl7oVdaCgvN/kd
            DD4uvGcO7YqFTemrI1sC6gii/PMf1whNAuBX9TDlgDe3hkzeZ1HrlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aUZXOTY3T0I0TVlJb1lH
            K0ZqQzlROFNCalludkcvcG9DVkgxWjk5b1g0CjJoekhEYk5pSTBRRWNUejR6eTht
            UTRxRy9SaVFMYlpDOFZuVzNaaGNyKzQKLS0tIEUrNmhJNHhIU2hvUm5PcTVnN2dn
            NFViYXBFZmhGM1ZPa2JTRUpkZHlVbUUKLgWgHHWhoiM3jN7a+xItwG1yu1KqjW0B
            7IfvpGAKkVMcLCixD1tvTcpDAyYJP/CnAb8+ieQt06A5uGfTnNQiGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-11-30T13:18:15Z"
    mac: ENC[AES256_GCM,data:7Sp9keS9Q42I4xWwZK1ZGCN4vRt83NzMH5V2u216jEt3HxUmZFWQ2jvd2PZt5+TQ0Q1YR289YS4TtCs6UlOPKiJW4s281A1cXYDNw0E9GZxVdBIXRiu/GOBZyud0OvzohQtXnMJuAzIB6IQrGCRY6X5yWnEustKdv8lvBwPra38=,iv:aRz1UYV0EB1GgLehkMniVaIqmvX6niApWBc11x+Cx8Q=,tag:B+e6yiVePyjRO8t93S5TfQ==,type:str]
    version: 3.11.0
