apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:nxOkO3fGuSMNN3h3vANitRUlNXdQ87DmRnNi2oS4wEjt4yg9Xj6xYhDCxA==,iv:OJlCj4LLdFlCiKh8/+uf6MGFl1fOHKhtBv0KUk4vVLY=,tag:Vxkag8Eqz2VCgWNS45hdEg==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaGJUMEo3c2F2ZGUwVDhI
            ZDVpVDlpY3FJZFR0NTVrMDZBYkNmZ2R3SldjClhZYUJ6VW90a2ZqM2VBdHFwRGxY
            S0NDeGRqTEhjUy9pL0xjTWtyOTlTV3cKLS0tIFQ2NEdiWXBXVHVERHBndU9xZVJM
            R2M1cFpiZk1sd1JDeFcwTGYyV3MxenMK8FBvGO7SGm2wkZ1km1R93Npw6guUIQPO
            UCtcGYdi9MVRR3JoxukaWJxcqvSFsj4wtXqzWbTEztmaqDLz4Q1dMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T13:34:45Z"
    mac: ENC[AES256_GCM,data:9rahq+z/tqdUtEx6JoJ+BDhaT+L6IZXM1DGJTCLGMt7xLbIy5zKVCur8aAxNlefQjvK3DM+soXRD3FoR9OG+SY1X8+GBoTXCRshNuxQNkf5OzrSqFubtiNWLsPgS7Fc/cVS7mAGatDeBBoqfM9SRVHEieYpA0ZcuPRWN7s+Zk/0=,iv:34yrlTBwoeU4Q9e9QhYJXhm/FI5odhZmOCLDu8sfTp4=,tag:wjGnDISQErh8qKPmbuFTYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
