apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:nxOkO3fGuSMNN3h3vANitRUlNXdQ87DmRnNi2oS4wEjt4yg9Xj6xYhDCxA==,iv:OJlCj4LLdFlCiKh8/+uf6MGFl1fOHKhtBv0KUk4vVLY=,tag:Vxkag8Eqz2VCgWNS45hdEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTak9qYUVYaTFGQWh6TlZj
            aHAwU01UaUVSeGpiSWwvTG1COElZUDQ3VVhVCmRkcFhNMGg4SW1vMm9MQkdDN2Uz
            WG9PempPTTlaV0RWeHBDZXlCZmVUWFkKLS0tIEU5MEJxK1gzdlRIVGdDRENVU3pq
            M2NWUXA2YWlTckRzV05qencwSUR2RW8KZAT/FGZDjbukSCIvZYzCwl5x50itwNIH
            zqIvhaesIFrOv3yCxPgFhI1FKMf0nbYP57QuEaYLkiSZ4JtMV/M31Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ2dpaXd2R2t4c1RxMTg4
            eXAyRGszNzZObXIvVjJRVGNKeDEzUFY5N1I0CjRIYXo5MnVHck9nOUQ3NFZCVm1m
            eXV1aE1OenNQWVduN3JZZlBEYUZGU1kKLS0tIFN2aUhVajNINjdQSHU4SkJaN0dQ
            YWR1Q0RiZ3BPOThRNS9nOU53YWlCQncKKRNo2rp9RH7aUhYBxi/WgyNj0Pk51Wgh
            81MGu9AQyxEs+u1GPqDkQnAG6d4YgrDA91GxPxGWdvOdcPMEJrRKwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-03-19T13:34:45Z"
    mac: ENC[AES256_GCM,data:9rahq+z/tqdUtEx6JoJ+BDhaT+L6IZXM1DGJTCLGMt7xLbIy5zKVCur8aAxNlefQjvK3DM+soXRD3FoR9OG+SY1X8+GBoTXCRshNuxQNkf5OzrSqFubtiNWLsPgS7Fc/cVS7mAGatDeBBoqfM9SRVHEieYpA0ZcuPRWN7s+Zk/0=,iv:34yrlTBwoeU4Q9e9QhYJXhm/FI5odhZmOCLDu8sfTp4=,tag:wjGnDISQErh8qKPmbuFTYQ==,type:str]
    version: 3.12.2
