apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Statistics database and configuration (~1Gi). Alt: 5Gi (extensive history)
  storageClassName: longhorn
