apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: "7.1.288"  # Check https://artifacthub.io/packages/helm/emberstack/reflector for latest
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: reflector
  values:
    # Resource limits
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi

    # RBAC - Reflector needs cluster-wide permissions to watch/copy secrets
    rbac:
      enabled: true

    # Configuration
    configuration:
      logging:
        minimumLevel: Information
