apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep-chrome
  namespace: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep
      component: chrome
  template:
    metadata:
      labels:
        app: karakeep
        component: chrome
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      containers:
        - name: chrome
          image: gcr.io/zenika-hub/alpine-chrome:124
          args:
            - "--no-sandbox"
            - "--disable-gpu"
            - "--disable-dev-shm-usage"
            - "--remote-debugging-address=0.0.0.0"
            - "--remote-debugging-port=9222"
            - "--hide-scrollbars"
          ports:
            - name: http
              containerPort: 9222
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - SYS_ADMIN
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
