apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage-web.yaml
  - storage-meilisearch.yaml
  - storage-meilisearch-v113.yaml
  - deployment-web.yaml
  - deployment-meilisearch.yaml
  - deployment-chrome.yaml
  - service-web.yaml
  - service-meilisearch.yaml
  - service-chrome.yaml
  - ingress.yaml
  - secret.yaml
