apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:924pLvkAP1+Zscen/O95wavxz7+Owvqw/ihqdg98NIUO+2MpO7gRV2PMLIvtN+YX0Pgsubz3McRMmZWjl6D/4zhxdJfl363g6bn0cn1TYq9ouClW0BxrRVAYvTdDKFIG3axJ/0S8dqpxZ7uZHrVvXe0z2U5gViHNj1TK4qrZl/ajiRKOoJnqA8IAWoom4yNAfW9lImsLz7IF8WW10N7jv3zLHC+lTX//TcVN,iv:lB3Kr/8+ipDqMXT7SkW750Y/geKVxOeciK2PGZPRRIY=,tag:9kJN2QADifABZ+cJPP0rZw==,type:str]
    meili-master-key: ENC[AES256_GCM,data:krqX+Ipb0FCljhA0OvVudnWTFF63pNVvQqykyF8js8WU6SecAaIOSMwfGv/bY8yGJ2UJvdy5nhCVfi/s0WBPg6CHyz4pawjdtlzy9Jyapm6rGRHK/yusCQBhUS1zVnKz1Vz2JihKC2+2QDVyV/MHvhIa4CT1SmDAy7wxfJcSehykEpAQsjq8VVo9u8M/C3/JP1m6Wj1faDvp2PxTxUcKxnWxdkWrL9FZny6b,iv:k/JZCtzoL1Kb6IX2jkm5fHcEIoJBvUJ9i0qzE2goA+Y=,tag:ltELWxWqNUynzXELHMlWLA==,type:str]
    openai-api-key: ENC[AES256_GCM,data:yBgnd1kLMps36TLw0x7hToBBKZTwzmb1FlqFJ0dvI+jZcaZc94R2zopuj451N49+GqNtVw==,iv:lLQ9PFjIkLzqNeq5mRUHIyK+SshWBvYrqHNfk9hidrQ=,tag:vjQJmYBF7wcQUHq3eWcTbg==,type:str]
    openai-base-url: ENC[AES256_GCM,data:MWY4hktXWJ+Mdvngl+dwjcvJsryri9GWalU=,iv:8YMwNUwZudr/XBdUVQ7UeXe8e+yZkngP1vn35BaPnVA=,tag:v/xW1RR5p6BlBWH3ZgHntQ==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWXhScFl3U21EMGdTYVFE
            dTNlMFVQUXBaajB5TktNVUEycm1YMmV5TVY4ClNXd3FTeXdQTU9qRzJjbXFneDl0
            T3REZ0RWSXp0TGU4WFl6MVJRUDhEV0EKLS0tIGwyaWFnek9MaHJLT2JGVERjdWpN
            N3hsOGxaSzVPbFdLLzFyeDhtWTBOaVkKyZVGJsomg/uzc9heOS/DL1JgNFz4+eyU
            lUKnV42/XXrQCcf/9Ug6jkgg5C87LHTdlQJ+2QFNVXcmUmoL2qytxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T16:08:51Z"
    mac: ENC[AES256_GCM,data:g/DbzlZLlEjFZHZNZlfPhKY9aLUr6c69mKqmVSsAITbplo2zIcf2YeaGF46HBrmZnUuw2Wf4Wrp9WsyqcrE9UyX4aHWj2raFLeG0XpdS9bROQ9nnN7oX5D+VutVK+wO08Db7rXYHuZpi4Vpj1TGHweCcXfk3zeGymdxcHrwa7f4=,iv:vXTkC7G2Qve6X8zNgBy5VlymBBStsXnKtGbCgGtFJOY=,tag:4VkshpaRhGB2Q3LxQBt7fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
