apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:rX5dSvrT4kjXCvh1t+RAAhf2NFzEkJNNYZ88G9gcCp7+RkGjhxRhk+s1WAd2rcRy,iv:rOjLUe9NM8b0ImCp24NZT9U8rVcT4F8jGYOxyPl0uaM=,tag:Cy2tFjnV0PHU00OUyKvk0w==,type:str]
    meili-master-key: ENC[AES256_GCM,data:IBxpKEBSWqMiBqqK6H0TknQp+KiuOo6SvYnq8MfQc1ubDMy+NZ6tkJBD+W2KNQDG,iv:h7b0VBQrTbZjI6iUAIEBIXPDyOV+IP00GISy77VHc8w=,tag:hDCsYkof+g7/w4gQ2Xx3ug==,type:str]
    openai-api-key: ENC[AES256_GCM,data:3gHco282l4zx38gN69S0P9fa8LoFlkoQcbvJk7RcNXnO0jlSn0+Po23XtdHJi3S24pzycBYgibMoKARjQFT8NtrHO999M+KET11+ZkoBuQ4VvqX+7mBWdjHnohgVTqDEeiHXOILzrLqgJaCt0be6v/bw0DErPXGzeoOfq2YxGvwwsdke/IujM++VqPdYtgShn1CLX7kRHXxGEPTmsAq6KZMGFYc=,iv:h34J1keU+RaZEQvi6cf1vO8v0wpB8442eJ3Qk8yK9Os=,tag:u8pBSclavHqHEcDjncuAqQ==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY1R0R2wrNkp1V0h2Qlpl
            REgvUGN0WldvQWJNbW1OQSt2ZVk2blMvQUg4Cjd6NUV4QWJsYnlzS1pYM0Rkb0Jk
            K2RjeG1ieVdhU1p3eElxQlJGYzRmMlUKLS0tIFpzYWE4TmRDQWtxckl6Y3Z4M0Vj
            WWxMZ3JrQUc4dUYzL0l3eTFWTk11bWsKH/UKTCNdu9qvMD09x6WwRfKvFNjB88eE
            Qtyzz3Nrge8/iucLNZx5OFRJr4RDU1e8cP2RAL4IqpExfUvOTtqP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T09:08:39Z"
    mac: ENC[AES256_GCM,data:1LiUP0gMTi42hbkewLMJ8xULNGGK4vrRM1ma50inmbDvZ727hqBGdX3WYSFoJCbMpcganuzQAiHwn7wm8i7FApvVimpnHzor46McWV81faKN/fDN9rRNbKOafvI1FEdsNQ/EvQ8DaTwJQ0ZY6F2JNQExds86wiP47ogTDfe4QD0=,iv:yHPszkgIjg2SZUDL3cpTyj7CGAfyQz2fzbGLbD8JQJA=,tag:xC3cRol7zf2YhUhxLhYzUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
