apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:5oRvQW2X3KdffTlN71sH4ZyP4nUOir8hdRpK5iDbANJbJYavC19NWRciCMo=,iv:cMN38ChRLihnafSlVf3OAf5ej5Av7JbAW4eoPfaCbe8=,tag:o8PFu0S4BlNtf3Tb0WGi4w==,type:str]
    meili-master-key: ENC[AES256_GCM,data:eVs3oM/ZPVsP5OA5Y4jf7WPoC8aF8rniysF70VRFdYreWHwYz3u3aQxUYNMdFOFy,iv:JYkk1om1uw0VP7N5CVhENSlRgMXuOk5xVr7/YNS8KZo=,tag:CjeSRBN5eyt14xwR9VTycA==,type:str]
    openai-api-key: ENC[AES256_GCM,data:FVh9IjX1chLoX50eZZG9x9TEPTPULO8/l+BqhdrebldiMCue2o/z82J9jxQa9ZxflsLV4g==,iv:c4tpr2aWIDByeY/O0v26Ui+wMHh0XevxRKUnI9zFJa8=,tag:oLAd5RROg6CkXwr58kajcg==,type:str]
    openai-base-url: ENC[AES256_GCM,data:0J//w8dlrziEoKdOg60P5sBhsCB1zek7IOQ=,iv:3stAxLn6XCBwxYuE+IDv2aaSpI8gZ6eP8VJhizGR5C0=,tag:2cILhuZ/M40vpVyG10pQog==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSHZKUCt6cEpGeWpRalU3
            UHZIQno5Sjh0Mms4WEFMWUovNEpseGp0bnd3CmRJRFgzRE9wbTNSS1U1U3lHdTFJ
            cExBM2tvMU9wZVJucHJPaEIxRXdTQ3cKLS0tIERRUlo2SlhyZ3FJc0N3V0J0QVhV
            WFBCbmIyUnJRdVJvZGdpZHI1N3FyMzgKZvj941viK8ZNw4AvxLb071UZ+pyMA45h
            J8KTJoASxjCyQCZM1kN881wkTjV5GbzaKGe0qYRVQRhTtcG//zuVXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T10:05:31Z"
    mac: ENC[AES256_GCM,data:QZuF86apVS3pYZSdGx1KdioSEOh4IyeCCmMcYGIFT5FQPGs8/QglgJqOPzh6u/e86RjxEPn90NYhW4IBeJDw81/DomeHsXlvB22frcA08ugAsbLXlmp/G3F/W+cKXlj0qeL3jXF5C73qJnK0Oex3XAbdTDf02x3+Iwkwb18dib8=,iv:uZ6FzCQPbFEDl8hKhxFxKZL5pnKQO/vAoLmMJEIsssA=,tag:wgQgrFK6HsSYdog66VgRcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
