apiVersion: v1
kind: Service
metadata:
  name: karakeep-web
  namespace: karakeep
spec:
  type: ClusterIP
  selector:
    app: karakeep
    component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
