apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-web-data
  namespace: karakeep
  annotations:
    longhorn.io/replicas: "2"
    recurring-job-selectors.longhorn.io: '[{"name":"snapshot-daily", "isGroup":false}]'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
