apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - longhorn-user-secret.yaml
  - service.yaml
  - deployment.yaml
  - bucket-job.yaml
  - longhorn-user-job.yaml
  - networkpolicy.yaml
