apiVersion: v1
kind: Secret
metadata:
    name: longhorn-minio-credentials
    namespace: backup-target
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:1aLd1sYNSTIJjVIxENfbh6C6THM=,iv:qPf7iZxNNsPnZPrOGRva6XvI2oODr8rif0KHtLr8Zq0=,tag:kDiDFoahulc4OdDGJO5xYw==,type:str]
    secret-key: ENC[AES256_GCM,data:sQzeQUg8mPAhlfRIyCFwO5huIDvdTNAD66wl0caho6CkRqww8exm6A==,iv:ig78YmoWB1wajwEVNYHTBZ+H1v2R3iHe7KS+00i+xB8=,tag:4oLWOKheMr2MWn/y8FYqiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNjFPRHFUb0NrTURMOFd3
            N2Q0MEM1UnBRZUZDVVVUNzFhdmwwaXRuUEh3CnVQall4RFZ1NTBidjJQNmVOdW9k
            bWRYa3I2MytmMHNmMFlaNVNrbXBLRkEKLS0tIERmWTBpcitxak1UQVE4Q0kyejRr
            a0NQVGNmdnVDMWxPajdZbjk4K2lWTTQKC4dEXyI3MrUgL01ml4Srms3GN6sBSLif
            yistB2yxxH6iw76XCZXb3c+kAYk/zKEQMmrfOkSgP5B1Z8ri8/Pyxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWG4rTVUvWURwS3NYSENN
            SncwT0hDYUwxWTB3Y0F2VkllUXdnQy9pUWdFClZVd1Z5YzY5NmFJVUxKaGY2VGVv
            UHZ4QllqdlhOTVUyTmxlcXJIdUtQbEkKLS0tIFRheUNkRFAvS2JFaEVWWVhFODlx
            RHhQd25NNTdSRU0vV05sc0dGbFB5SmMKBVBRGvjxTkQ6RkIFT1oGsz+j6oBYpXtY
            E11pYHEGWS2hp7YOAcThOlYkrt8TwOanBGeUvxqJUHuT+goK+S3RNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T20:33:56Z"
    mac: ENC[AES256_GCM,data:ycCKKR0Zb1lfRH0O++V9ypV+tnwS9GuRWYK3avYn1BL/kAiFsXbAuBwbEhwj9oPc+ERwm6tdEfmcs0bJNVH2HgCoWCFuxSNAmipUYHt/N5c8NfdNDd2aYI7DJvW7jJve7ki6y+NrScaTwi6A1BrChf5SlV+RJAqs+/FZXdtKPTw=,iv:LWiLu/iIqtteNRype91UPdvLMjc6QC/GGHY1JRI06t8=,tag:ByB9Ti3rHjaBVKKrKcATnQ==,type:str]
    version: 3.13.1
