apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: backup-target
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:lAVhIlQa6UrTyPmXJ1beKxALf3+uaNmxWT1lo582/WWecvPQG4416g==,iv:upN2Nsux8TZEGU3+1wOAFQA6IlQORtyTt6G4qz90huI=,tag:oA45nGDB78SZcMCsDdB6Pw==,type:str]
    secret-key: ENC[AES256_GCM,data:+3usx90s/Jt93ezlmweG6ihXMy3UNJnSLOwKAY++pajKXQSaK+m4rXnkGXIy+TSguS2NLnEDPfMwALZw19mYnw==,iv:IT6yl+Pw5+gAZAVDW+5Bnb0DTj9RdCdESmnbW30X0h4=,tag:uFe31AoYNyDJCMIom3gMMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN2N0eTdGckVHTkdoR0Z0
            WEJnbnpNTEQ4aHpMb2tDVUFuc0hSeS8vTDM4ClQ1aVJvWWZYSzhwMWhrdTB0RTFG
            TEdMb0svTFRNVXVpWGJZd1gxSUk0a1UKLS0tIDFGbWwzdHQ0cDFtNFU5YTZZOUJ3
            bnMzcUhpNmNEbGpjdWNySllTbHpFWWsKjJ3fViWM28rAk9PRmH61NnkBM7eY001b
            9iT+Mof4Z6mRB8NkFJK6d/wJgA7l2CEOFP+/CxHy6KR1uHClnM2L7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMGdrQXE1R0hGRXhaVFR6
            elZPZHVFcGpmMG9YRWxOelJWYVVnbmp1SlVvCk94VmdTUFVWTTZvZWxYU2hpUWhH
            Y1JBY216b1MwL29JSnoyVlNxMUwzWlUKLS0tIHZkbS9QM2krUzQ4bGZwcWFjRE1w
            TXFZMFFRV3VLL2lxVDUvOEFlWnA0MFEKiRB6ixnZxNWqZi722I9zNbTKRHhZ/3L6
            w+IJ0FBTvrQ5U4gvgF/83CA8ODJPoWrijIyD/95z5wS3lLCCeZOD4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T20:04:16Z"
    mac: ENC[AES256_GCM,data:gRM58zOV4QzxGvvx9g3lDbE2AzzlKL4itFlgMaQq18Ab2KkXcHyy8f8mcLqt4kIZ6vYjfk1WWoiYU4rNj1wl1MAeqVsPThaXdUkKxBYTbd8wQvwAC56DmxvZ576XLRB2+YLi7V+fxEofESoPtkvNZL0RJbg+XboV0SaZqMBxCnI=,iv:r/5svZ+sPlkRYnXQjS9evM+3qi4dUuBP51BgzhzzwXg=,tag:3NNxFlLoJRLTM+U2c2Punw==,type:str]
    version: 3.13.1
