apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: flux-system
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: vikunja-vikunja
            patch: |
              - op: add
                path: /spec/replicas
                value: 0
              - op: replace
                path: /spec/template/spec/affinity
                value:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: kubernetes.io/hostname
                              operator: In
                              values:
                                - talos-awe-w01
          - target:
              kind: Deployment
              name: vikunja-vikunja-typesense
            patch: |
              - op: add
                path: /spec/replicas
                value: 0
              - op: replace
                path: /spec/template/spec/affinity
                value:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: kubernetes.io/hostname
                              operator: In
                              values:
                                - talos-awe-w01
