apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karakeep
resources:
  - ../../base/karakeep/
patches:
  - path: deployment-web-maintenance-patch.yaml
  - path: deployment-meilisearch-maintenance-patch.yaml
  - path: deployment-chrome-maintenance-patch.yaml
