apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bazarr
  namespace: media
  labels:
    app: bazarr
    release: monitoring-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
