apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # qBittorrent config/database (~1-3Gi actual). Alt: 10Gi (heavy torrent history)
  storageClassName: longhorn
