apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent
  namespace: media
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: qbittorrent
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
