apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti  # Media library ceiling for 2-node cluster (single replica = 1Ti actual). Alt: 500Gi (space-constrained), 2Ti (large library)
  storageClassName: longhorn-media
