apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi  # Reduced from 1Ti due to node storage constraints (max 236GB/456GB per node)
  storageClassName: longhorn-media
