apiVersion: v1
kind: Secret
metadata:
    name: renovate-github-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Tp5NcFIDLXEmm2ON92JkFYk4JINe/yjhHVF0V54NMmB3tFg3xTnrfg==,iv:h87bjbaVoHKfT3AFK/RVy8+yQsxzhNgzePmmbVUBGzQ=,tag:trYEDnTmlZm+t2rRG0HIEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycTdLY1pRU2tzWEdNTXc1
            Zk02WXdOVVlGeUlCdVNNdjVhOUVIWklQRUhRCmZkdDFMZy9XZHNtOC9VUnVaNzNB
            bXp0bUFhdWFsbDNJNmlWUUJZQUdrcUEKLS0tIC9kTzJJTDRRSlJTREM5SWRpMW0z
            WDZMUGczRDJ2OFQvZER4bkd5ang4QXcK1Way30dT34hqpgkRogCX0dTYllVQ2tAF
            OApbd5Ns2owzzXoXHfI55seBEUhaR/OViuAxrMssqroVZLhc1bOdvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR2JjaGdaRGh3NHZqNGZk
            bVZVVHNuc1E4Vzh4dWFGM0xTMWxVMm53Q20wCnliSnhzajdOM2NZeWFXNW45Vnhq
            YkJxQyt6S1dhdmZ1T3FtZ1J4T3dVS00KLS0tIGZQWDZ5MENzSk9TRlZXQVJWZVZW
            VGhtWXJXRHkzWmIzdGUrdkFFa2VYUkEK8gthOiYg7PWxjIukKBfqsgniq7cHeGiy
            RM5mnJt4itNIvZCx1mb3aNqFXtKyOzZCRH9pc1Go8sgS8gm3AY+w7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-01T14:22:40Z"
    mac: ENC[AES256_GCM,data:uh2PzKHZqWO/+8v/exY8Fuf+epg/MbehoI/1I3nAL5k7gPZbDWGqEzgC1fQAuIH4gHeEoyTWkiOkFVOi6J23tfqm/2NsI5WX0sV7cNV6MLjqYlf8oBPjbBjGLH8kutp421nXbTpN5Vj6AIbfDnBvVtcsb/0q6hrK4u8Mnu0qjFw=,iv:Em59fsU4IqNxp7DNobYpwU4jIzt1sm4RHQiFpBYjWRg=,tag:NNmEfZ7KC2EHbDhZCug6Eg==,type:str]
    version: 3.11.0
