apiVersion: v1
kind: Secret
metadata:
    name: renovate-github-token
    namespace: renovate
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:HzXAQjgyYkiJoPLAkyUx9TTTZRbPIzznLQ1UexR4KjcS6NSkFPW+/g==,iv:PL9GbVJCCdjemgrRi0Q3/JAnVWPRwk4yl4la2W40Se8=,tag:SjfonPxwByLWMfZXspY0Eg==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaDhGYVZhZlJvL0IzWDJX
            R2ZjekZ3NHB0akJZQjR3eHhibjJ6WTMxRWdBCkVRUGVxNHN2MzZyQzNYc2VqK0wr
            SjZWV2xlczJrOExOSjAvV2ZpeTUxaEUKLS0tIEsyeUFRRTV4dGFObzVGblpCTDZT
            VWZIRktmdGx6SG84UFAyTEpIMDYydU0Kw0mTHsL1L20RcF76Ys7Hf9brcwEF3iIh
            e9gSluY0JIsgch0dj2kkBA03MAVpKtOLTV3GqlcPrwkrZxszmEut3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:02:47Z"
    mac: ENC[AES256_GCM,data:gDz914aesg/WKv/FhfaOdTHl3nhEPXn6e+gRtle7qntt6HMG/PaD44jObAgEWu2nATFwwyrXlFjA1IXnzSlyw+DC5UUpLy8Wy5aRF9n6/oPczD7r4+qpfQpRZg1QosbHYZi6DLsX7YOn9nERzjm98heZm7gRA2R4IzodscezBwU=,iv:XhBz/RTrQZsCfOSNGAqFZkh5PExWYvq/ewmydA8FC/c=,tag:m1SjTBX1jEFQgggdEVpM2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
