apiVersion: v1
kind: Secret
metadata:
    name: renovate-github-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Tp5NcFIDLXEmm2ON92JkFYk4JINe/yjhHVF0V54NMmB3tFg3xTnrfg==,iv:h87bjbaVoHKfT3AFK/RVy8+yQsxzhNgzePmmbVUBGzQ=,tag:trYEDnTmlZm+t2rRG0HIEw==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSzE2NkpoWFZoVDZ4YXNP
            M2RTNjMwd2xsWFZPanJQTk9jVkhOdGpaVVdjCkRmdERYQ1UvWGVrL2xGTlFma1hz
            UjVvODkwTVpIUmg2bE5EMUVaT0psZmsKLS0tIFc1RDg4dlZJcmh2MW9xSVlycDds
            TFBmaFA2dHJobkJzWExGNnBrTkJ2VjgKccVZwRInRhf38IvdSpsLVLd+TbtbFks8
            2eGbk9PE3mOrTprd01TNSXMH2uLANJhedL0tUKt7gd4YFKqOyckQSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:22:40Z"
    mac: ENC[AES256_GCM,data:uh2PzKHZqWO/+8v/exY8Fuf+epg/MbehoI/1I3nAL5k7gPZbDWGqEzgC1fQAuIH4gHeEoyTWkiOkFVOi6J23tfqm/2NsI5WX0sV7cNV6MLjqYlf8oBPjbBjGLH8kutp421nXbTpN5Vj6AIbfDnBvVtcsb/0q6hrK4u8Mnu0qjFw=,iv:Em59fsU4IqNxp7DNobYpwU4jIzt1sm4RHQiFpBYjWRg=,tag:NNmEfZ7KC2EHbDhZCug6Eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
