apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi