apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: pihole
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: pihole/pihole
      tag: "2024.07.0"
      pullPolicy: IfNotPresent
    DNS1: "1.1.1.1"
    DNS2: "9.9.9.9"
    DNS3: "8.8.8.8"
    DNS4: "8.8.4.4"
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-data-pvc
      size: 5Gi
    serviceWeb:
      type: ClusterIP
      port: 80
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: 192.168.0.200
      port: 53
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - pihole.sarma.xyz
      tls:
        - secretName: pihole-tls
          hosts:
            - pihole.sarma.xyz

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      runAsNonRoot: true
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

    extraEnvVars:
      TZ: "Europe/Zagreb"
      DNSSEC: "true"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
    adlists:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://mirror1.malwaredomains.com/files/justdomains
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    dhcp:
      enabled: false