apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
type: Opaque
data:
    WEBPASSWORD: ENC[AES256_GCM,data:25UOVAY/II5qRF989274iN5A5NOmItdm,iv:rM4PhseOCEm3Y4gywTITY5ZeMI2tWGlCu7ixHZ/hOHw=,tag:++aUh+QzvVb1fqioMn0oeg==,type:str]
sops:
    age:
        - recipient: age1hnjqvvs9nce37lxapmwctzgnfhwrvxcgejy8ut93n2w3mtt82q5qv6ng9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmxDS1lqYnFJT1FWU3Fv
            R3lZamNRUXRRcmlNOTJ0d1RQbUxrQ3lwSlNzCjFodGRoTlVoaFVXaXFSdlQyNUhX
            aUZQdEVkeEcvOFF0ODdnOWRoRk9uUjQKLS0tIEVpOE1UV3pEbEtMSFpkZC9jQUJn
            cU44WFNWalZraVQyaDl1NjNOWjRkYncK4xzjnfu2rhn15HaAKp9QQ0tLYCJ2J7t0
            RUXaeRyskxz7suk6j3gSYF9x+6NBw/q3+s05y6U4DDNIFQAqDpsquw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T10:23:04Z"
    mac: ENC[AES256_GCM,data:iMutrDKyJtdbs2zCyw1xA8znHYH+BZF+WHRuBevsvKODiGIE+nzze1spbN36hSDH414GG2UKh6woU46881QBTL6EIR61hD0aO62fS+whyhBUkK5XUa8+0CqndvP5FWQQWHo8Eg0/LR6N5qRAjF+9ZX9e9UWdUBIMLhVzLdLs/1w=,iv:FiZGlNl4H9B1h3T1DuLQyAK5w+aFXCroprGuHv6sCOk=,tag:0sMoz20C14Q1jH9jQFFpCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
