apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headscale-tls
  namespace: headscale
spec:
  secretName: headscale-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - headscale.markonakic.xyz