apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@markonakic.xyz
    privateKeySecretRef:
      name: letsencrypt-dns01
    solvers:
    - dns01:
        manual: {}