---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: ./deploy/porkbun-webhook
      sourceRef:
        kind: GitRepository
        name: porkbun-webhook
        namespace: cert-manager
      interval: 1h
  values:
    groupName: acme.porkbun.com
    image:
      repository: ghcr.io/mdonoughe/porkbun-webhook
      tag: v0.1.5
    # Use our existing porkbun-api-key secret
    secretName: porkbun-api-key
