---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-porkbun
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-porkbun:flowcontrol-solver
rules:
  - apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - prioritylevelconfigurations
      - flowschemas
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-porkbun:flowcontrol-solver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-porkbun:flowcontrol-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-porkbun
    namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-porkbun:secret-reader
  namespace: cert-manager
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - porkbun-api-key
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-porkbun:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-porkbun:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-porkbun
    namespace: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-porkbun
  namespace: cert-manager
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-porkbun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-porkbun
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-porkbun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-webhook-porkbun
  template:
    metadata:
      labels:
        app: cert-manager-webhook-porkbun
    spec:
      serviceAccountName: cert-manager-webhook-porkbun
      containers:
        - name: cert-manager-webhook-porkbun
          image: docker.io/talinx/cert-manager-webhook-porkbun:latest
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          env:
            - name: GROUP_NAME
              value: acme.porkbun.com
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-porkbun-webhook-tls
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.porkbun.com
  labels:
    app: cert-manager-webhook-porkbun
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/cert-manager-webhook-porkbun-webhook-tls
spec:
  group: acme.porkbun.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-porkbun
    namespace: cert-manager
  version: v1alpha1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-porkbun-webhook-tls
  namespace: cert-manager
spec:
  secretName: cert-manager-webhook-porkbun-webhook-tls
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - cert-manager
  commonName: cert-manager-webhook-porkbun.cert-manager.svc
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - cert-manager-webhook-porkbun
    - cert-manager-webhook-porkbun.cert-manager
    - cert-manager-webhook-porkbun.cert-manager.svc
    - cert-manager-webhook-porkbun.cert-manager.svc.cluster.local
  issuerRef:
    name: cert-manager-selfsign
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-selfsign
spec:
  selfSigned: {}
