apiVersion: v1
kind: Secret
metadata:
    name: porkbun-api-key
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:csnsP6QrdxerOtvN7khRzRrIvtQ1zj1fiTgMA9wKBlqwemioT7NoTa5ZW2HsAs5Sfo+RKAVe/S8iEnhgXyeP/Qw0Ifc=,iv:50y7uvGg//iuiXqWAR8vYFGZk/m5bXFlmnE7CUbAnXI=,tag:JEupB0ZKvpByCiGw/Foqcg==,type:str]
    secret-key: ENC[AES256_GCM,data:O7FtrGU7NMpjaSCg2OukRfslhV3zP729pvxhKcWwfy2wt43mEgRWvaaou3882MGEcqhGiR2tqE5vhoq20FN7Lv7lQQU=,iv:q7FodjSpvh03USIAXPOUr4DftMnqnWKcf96wTiU47o8=,tag:aJkuke7fPoSR2u9N+qwb7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndEgwcGNpUlp2V1pxYjlS
            UjZ3NnhLZ21xM2x4akd4UkQ3cTdFaHlSR0hZClJUNmJ3a1A2dWw0VWNKWmd6QjVM
            YXR4WWVVdC9udFdVZ2M4anZSMXBvYVUKLS0tIDBLSkF1eWV2TU9lRWVZUUNCZEE5
            bTRkR2VvVWdqVGpTUW42N1FZcjVvZEkKbzhvreJO3N2wg6T12l+87PfnKpvzI/wp
            2ZB5Nx20+wJj5hdTNt1TOpwBSBz7kVCyp6GN6tHmjeEwG7Wy5bhd5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQmh0VFBvZ2pFM1FkT0JM
            Z1lvU2JLOXNndFBaMjZmRExmV2V3NjVDS21nCnQwQ2R1VUI4Qks5K2pOWGM5MVRI
            ZXV1L2Z2ZEEyeCs3aXFtVjZVcWxMWjAKLS0tIFZKbkpOSEhybnAwOHNoSjRJUmU0
            WDNRNlhBZTFEV2wwd2hFUmdRTExub3MK+eK+rgcJj9nXu9MK9OmjdnUbIHxBW+Ly
            +4nAfKhkAXHOFC1wjITgjxipYgQGRwdokGeKSheOPx1EA6DJHmUMnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-01T07:24:37Z"
    mac: ENC[AES256_GCM,data:9nZNGIdeO4SzIdexXgsxr8/7DZgtntWlZ4wrd/lrQgDxsv1087UWOLvvWRWQq4qFMXvnnyKikuzIqbj72x6qzG6bqUwVjozF2DQM6X7odXBY+Z4A/2UiIHQAvgD1yetwZCa82QLtKzuZr2QliK0dWVEeJbrrdZ/1pT7pwq4hJJ8=,iv:ifnreK1f9Qrh3Ss6Dm12w1/9EFs3BYbYbdZm5Jin8bo=,tag:oIdiPaxgxEJA8eDh1M7+Rg==,type:str]
    version: 3.11.0
