apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: vaultwarden
      version: "1.2.6"
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: flux-system
  targetNamespace: vaultwarden
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: vaultwarden/server
      tag: 1.32.7-alpine

    env:
      TZ: "Europe/Belgrade"
      DOMAIN: "https://vault.sarma.love"
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "true"
      SHOW_PASSWORD_HINT: "false"

    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    ingress:
      enabled: false
