apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-credentials
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+UCfnlT3BXnUt8EBM5RCVikXvAU=,iv:7UuwxcV78gFVqsgRxiG+CPnFiyJqclvfqaKifyMkork=,tag:fM+LDrzxP8UJeBk5oV324A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sLXice4NkCpHkgp0yN+UMB+KLkGcXgLOSK8d0r4tiKvGEASOpcZJtQ==,iv:hYdZlFZjjuDo2AblDHv84x4jUE1OxJko13/tHSZrrjQ=,tag:kfA6Kgg7XJeUksd2t6opLA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:R+vACLk3i5gOXFBH/yKIvvK+kHuIBhoguXNuXT0v30yCfNWwCUEtw2oVU/s9kWYUeg==,iv:M6+eLJZ5dvIYqBXozkphBsvVuJgf0etpDDYQX7oKtlA=,tag:rV1sUSlLLs3Tvq8vMQWRuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT2o3UHNGT1N3d1pQWlYv
            REwyeGo2UlgrR1BCakxEckFrS0VKOUF0RkZvCllUQThkdGhLQjl2R1BDV2g4cWlk
            QVNQWXpNMDRtanZtNk9iV1dzRVhUbmsKLS0tIEQxWER5cm03RDduaUo1RUhub3FZ
            T2Z3NmxJclh1dkh0emNmQ29ZNzZnMmsKMNVn0LDMh5O2bO9ySMio0d4Ow+tCAQF5
            Wp5y6E3zd0jaM/r256B8I1YAy07qE3nsDkAuKlKcgiA7+slLJNroGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TGkvZjFRbWVFdFVIZkV4
            QlhqaXh3Ly9yaTlDa3pMRW1GTDNRbzVOQTFRCm8rUHFXVDhhdmpFb29HTHlnQ1Ay
            VUJpNDVmMkxyU0NSamNZLzllWVMvV2MKLS0tIHpVT3M4ZjRLMmVUZGF2SEtrd2h3
            MVF1ckpNMC9PVm1wd1F6S01icjh3UVEK7pRlj/lqaqGFcUqZNmKEyzp6sOjuLhBM
            RhUp67nOHRnHOi5cA9IQfi8HNnAngtVsjG2LCR8qgNo2CNd2FW29Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjzsvxjepjgy9csel2kv50ww7ymq35976y76k8tw27cuw773zamq9d99rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T20:33:56Z"
    mac: ENC[AES256_GCM,data:Dn17sdR/CTR4Of4KPxVoy8qxD6+UhGd4ZluDztE7y4EexAN7211hogDYyR84fcxX6dc36FT+sZmXC2Sfc4hWpVLj34XRVCD/idTUB4bv7ZOP/JqZ1I2Fa0SOznvY1Lh7m2vCmZ/LD1NMLkU7I6Wbn/jrZXwJ5xGHDzWeBrTOIBE=,iv:9yIzkAi0CdDpbvQO9JTYQz4W/X/5d2jvlPHPjM7wzRc=,tag:tu2O8UQ/Vw9bfRJPQyQHDg==,type:str]
    version: 3.13.1
